<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'itbz\\utils' => $vendorDir . '/itbz/utils/src/',
    'itbz\\stb' => $vendorDir . '/itbz/stb/src/',
    'itbz\\phplibphone' => $vendorDir . '/itbz/phplibphone/src/',
    'itbz\\phplibaddress' => $vendorDir . '/itbz/phplibaddress/src/',
    'itbz\\phpcountry' => $vendorDir . '/itbz/phpcountry/src/',
    'itbz\\libmergepdf' => $vendorDir . '/itbz/libmergepdf/src/',
    'itbz\\httpio' => $vendorDir . '/itbz/httpio/src/',
    'itbz\\datamapper' => $vendorDir . '/itbz/datamapper/src/',
    'itbz\\Cache' => $vendorDir . '/itbz/Cache/src/',
    'fpdi' => $vendorDir . '/itbz/fpdi/src/',
    'fpdf' => $vendorDir . '/itbz/fpdf/src/',
    'emberlabs\\gravatarlib\\' => $vendorDir . '/emberlabs/gravatarlib/',
    'Twig_' => $vendorDir . '/twig/twig/lib/',
    'Pimple' => $vendorDir . '/pimple/pimple/lib/',
    'Phpass' => $vendorDir . '/rych/phpass/library/',
    'Monolog' => $vendorDir . '/monolog/monolog/src/',
    'Aura\\Router' => $vendorDir . '/Aura/Router/src/',
    'Aura\\Cli' => $vendorDir . '/Aura/Cli/src/',
    '' => $baseDir . '/src/',
);
