<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'EmailAddressValidator' => $baseDir . '/libs/AddedBytes/EmailAddressValidator/EmailAddressValidator.php',
    'EmailAddressValidatorTest' => $baseDir . '/libs/AddedBytes/EmailAddressValidator/tests/EmailAddressValidatorTest.php',
    'emberlabs\\GravatarLib\\Gravatar' => $baseDir . '/libs/emberlabs/gravatarlib/emberlabs/gravatarlib/Gravatar.php',
);
